---
name: tree-sitter-cli-win-fix
description: |
  The Tree-sitter CLI allows you to develop, test, and use Tree-sitter grammars from the command line. It works on
  MacOS, Linux, and Windows.
homepage: https://github.com/tree-sitter/tree-sitter/blob/master/cli/README.md
licenses:
  - MIT
languages: []
categories:
  - Compiler

source:
  id: pkg:github/tree-sitter/tree-sitter@v0.26.3
  asset:
    - target: win_x64
      file: tree-sitter-windows-x64.gz:tree-sitter-windows-x64.exe.gz
      bin: tree-sitter.exe

bin:
  tree-sitter: "{{source.asset.bin}}"
