#---
#name: clang-llvm
#description: |
#  The LLVM Project is a collection of modular and reusable compiler and toolchain technologies.
#  This package provides the Clang compiler and LLVM tools prebuilt for Windows (MSVC ABI).
#homepage: https://github.com/llvm/llvm-project
#licenses:
#  - Apache-2.0
#languages:
#  - C
#  - C++
#categories:
#  - Compiler
#
#source:
#  id: pkg:github/llvm/llvm-project@llvmorg-18.1.8
#  asset:
#    - target: win_x64
#      file: clang+llvm-{{ version | strip_prefix "llvmorg-" }}-x86_64-pc-windows-msvc.tar.xz
#      directory: clang+llvm-{{ version | strip_prefix "llvmorg-" }}-x86_64-pc-windows-msvc
#      bin:
#        clang: bin/clang.exe
#        clang-cl: bin/clang-cl.exe
#        clangd: bin/clangd.exe
#        llc: bin/llc.exe
#        opt: bin/opt.exe
#
#bin:
#  clang: "{{source.asset.bin.clang}}"
#  clang-cl: "{{source.asset.bin.clang-cl}}"
#  clangd: "{{source.asset.bin.clangd}}"
#  llc: "{{source.asset.bin.llc}}"
#  opt: "{{source.asset.bin.opt}}"
#
#neovim:
#  lspconfig: clangd
