#---
#name: gcc
#description: |
#  A custom GCC package made by yours truly
#homepage: https://github.com/niXman/mingw-builds-binaries/
#licenses:
#  - GPL-2.0
#languages:
#  - C
#categories:
#  - Runtime
#
#source:
#  id: pkg:generic/C/gcc@15.2.0
#  download:
#    - target: win
#      files:
#        gcc-15.2.0.7z: https://github.com/niXman/mingw-builds-binaries/releases/download/15.2.0-rt_v13-rev0/x86_64-15.2.0-release-win32-seh-ucrt-rt_v13-rev0.7z
#      bin: mingw64/bin/gcc.exe
# bin:
#  gcc: "{{source.download.bin}}"
