---
name: mingw-gcc
description: |
  GCC and G++ (MinGW-w64, UCRT, POSIX threads) from WinLibs.
homepage: https://github.com/brechtsanders/winlibs_mingw
licenses:
  - GPL-3.0
languages:
  - C
  - C++
categories:
  - Compiler
  - Runtime

source:
  id: pkg:generic/winlibs/mingw-gcc@15.2.0
  download:
    - target: win_x64
      files:
        winlibs-gcc.zip: https://github.com/brechtsanders/winlibs_mingw/releases/download/15.2.0posix-13.0.0-ucrt-r5/winlibs-x86_64-posix-seh-gcc-15.2.0-mingw-w64ucrt-13.0.0-r5.zip

bin:
  gcc: mingw64/bin/gcc.exe
  g++: mingw64/bin/g++.exe
